name: my_caliana
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  carousel_slider: ^5.0.0
  colorful_safe_area: ^1.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_riverpod: ^2.5.1
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.20.2
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
